apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "metricbeat.fullname" . }}-daemonset-modules
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ template "metricbeat.name" . }}
    app: {{ template "metricbeat.name" . }}
    chart: {{ template "metricbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  system.yml: |-
    - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        #- core
        #- diskio
        #- socket
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5      # include top 5 processes by CPU
        by_memory: 5   # include top 5 processes by memory
    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  kubernetes.yml: |-
    #----------------------------- Kubernetes Module -----------------------------
    # Node metrics, from kubelet:
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 10s
      hosts: ["localhost:10255"]
      enabled: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      #ssl.certificate_authorities:
      #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
      #ssl.certificate: "/etc/pki/client/cert.pem"
      #ssl.key: "/etc/pki/client/cert.key"

    # State metrics from kube-state-metrics service:
    - module: kubernetes
      enabled: true
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_statefulset
        - state_pod
        - state_container
      period: 10s
      hosts: ["kube-state-metrics.kube-system:8080"]

    # Kubernetes events
    - module: kubernetes
      enabled: true
      metricsets:
        - event
