apiVersion: v1
kind: Secret
metadata:
  name: {{ template "metricbeat.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: {{ template "metricbeat.name" . }}
    app: {{ template "metricbeat.name" . }}
    chart: {{ template "metricbeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  metricbeat.yml: {{ toYaml .Values.config | indent 4 | b64enc }}
